goods_armor_name = ['Костюм АО-1 «Бродяга»', 'Поношенный АО-2 «Странник»', 'Костюм АО-2 «Странник»',
                    'Комбинезон «Аврора-Б»', 'Комбинезон «Аврора» с противогазом', 'Комбинезон «Аврора»',
                    'Бандитский костюм с баллонами', 'Бронекостюм «Комбат-5М»', 'Пальто со шляпой',
                    'Маскировочный костюм «Смородина»', 'Маскировочный костюм', 'Защитный костюм «Псарь»',
                    'Бандитский костюм с противогазом', 'ИП-4м', 'Бандитский кожак', 'Модная куртка',
                    'Куртка с бронежилетом', 'Куртка с бронежилетом', 'Куртка', 'ЗК-1 «Отмычка»',
                    'Поношенный КИМ-99 «Янтарь»', 'КИМ-99 «Янтарь»', 'Поношенный "Клептоман"', 'Костюм «Клептоман»',
                    'Бандитский кожак', 'Комбинезон «КЗ-1»', 'Бронекостюм «КЗ-2»',
                    'Бандитский «Крот»', 'Костюм «Крот»', 'Поношенный «Грибник»', 'Комбинезон «Грибник»',
                    'Продвинутый ОЗК', 'Дождевик', 'Бандитский плащ', 'Охотничий плащ', 'Плащ', 'Костюм «Скаут»',
                    'Костюм «Горка-3»', 'Бронекостюм «Страйкер»', 'Бандитский костюм', 'Поношенный костюм «Траппер»',
                    'Костюм «Траппер»', 'Бронекостюм «Червь»', 'Комплект «Алтын»', 'Поношенный костюм АО-3 «Искатель»',
                    'Костюм АО-3 «Искатель»', 'Лечебный «Комбат»', 'Поношенный тяжелый бронекостюм «Громила»',
                    'Поношенный бронекостюм «Сокол»', 'Бронекостюм «Сокол»', 'Поношенный бронекостюм «Гоплит»',
                    'Бронекостюм «Гоплит»', 'КИМ-100 «Гранат»', 'КИМ-102 «Циркон»', 'КИМ-105 «Топаз»',
                    'КИМ-113 «Иолит»', 'КИМ-116 «Изумруд»', 'КИМ-85Д', 'Поношенный КИМ-99М «Малахит»',
                    'КИМ-99М «Малахит»', 'Бронекостюм «КЗ-3а»', 'Поношенный защитный костюм «Ворса»',
                    'Защитный костюм «Ворса»', 'Бронекостюм «Рысь»', 'Поношенный бронекостюм «Пересмешник»',
                    'Бронекостюм «Пересмешник»', 'Поношенный тяжелый бронекостюм «Восход»']
goods_weapon_name = ['АЕК-919К «Каштан»', 'АН-94 «Абакан»', 'АК-105', 'АК-74М', 'АКС-74', 'АКС-74У', 'АКС чистильщика',
                     'АКМ', 'АПС', 'Винтовка Мосина', 'БМ-16', 'Browning Hi-Power', 'СВТ-40', 'СКС-Т', 'СКС', 'СКТ-40',
                     'Cobray Terminator', 'СОК-94', '«Цунами»', 'ДП', 'FN SCAR-L', 'Форт-12', 'Franchi SPAS-12',
                     '«Гепард»', 'HK MP5K', 'HK UMP9', 'IMI Uzi', 'IMI Micro Uzi', 'IMI Mini Uzi', 'Ingram MAC-10',
                     'Карабин Мосина', 'Kbk wz. 88 Tantal', 'Поношенная L85A1', 'Поношенная L86A1', 'M1014', 'M16A1',
                     'M16A2', 'M16A3','M4A1', 'Mauser 98k', 'Mauser C96', 'Mossberg 590A1', 'МР-133', 'МР-153',
                     'Обрез БМ-16', 'Р-92','ПБ', 'ПММ', 'ПП-2000', 'ПП-91 «Кедр»', 'ППШ', 'Shorty 590',
                     'Поношенный SIG SG 550','Spectre M4', 'Steyr Scout', 'ТОЗ-34', 'ТТ', 'Vz.68 Scorpion',
                     'Walther MPK', 'Walther P99','Поношенный Winchester M70', 'Winchester M70']
goods_armor_icon = ['ao-1', 'ao-2-old', 'ao-2', 'aurora-b', 'aurora-m', 'aurora', 'balloon-b', 'bc', 'coat', 'currant',
                    'disguise', 'dogman', 'gas-mask-b', 'ip', 'jacket-b', 'jacket-m', 'jacket-mm', 'jacket-mm2',
                    'jacket', 'key', 'kim-99-old', 'kim-99', 'kleptoman-old', 'kleptoman', 'kojak-b', 'kz-1',
                    'kz-2', 'mole-b', 'mole', 'mushroom-old', 'mushroom', 'ozk', 'rain', 'raincoat-b', 'raincoat-m',
                    'raincoat', 'scout', 'slide', 'stryker', 'suit-b', 'trapper-old', 'trapper', 'worm',
                    'altyn', 'ao-3-old', 'ao-3', 'bc-m', 'bully-old', 'falcon-old', 'falcon', 'hoplite-old', 'hoplite',
                    'kim-100', 'kim-102', 'kim-105', 'kim-113', 'kim-116', 'kim-85d', 'kim-99m-old', 'kim-99m', 'kz-3a',
                    'lint-old', 'lint', 'lynx', 'mockingbird-old', 'mockingbird', 'sunrise-old']
goods_armor_ID = ['N-ao-1', 'N-ao-2-old', 'N-ao-2', 'N-aurora-b', 'N-aurora-m', 'N-aurora', 'N-balloon-b', 'N-bc',
                  'N-coat', 'N-currant', 'N-disguise', 'N-dogman', 'N-gas-mask-b', 'N-ip', 'N-jacket-b', 'N-jacket-m',
                  'N-jacket-mm', 'N-jacket-mm2', 'N-jacket', 'N-key', 'N-kim-99-old', 'N-kim-99', 'N-kleptoman-old',
                  'N-kleptoman', 'N-kojak-b', 'N-kz-1', 'N-kz-2', 'N-mole-b', 'N-mole', 'N-mushroom-old',
                  'N-mushroom', 'N-ozk', 'N-rain', 'N-raincoat-b', 'N-raincoat-m', 'N-raincoat', 'N-scout', 'N-slide',
                  'N-stryker', 'N-suit-b', 'N-trapper-old', 'N-trapper', 'N-worm', 'S-altyn',
                  'S-ao-3-old', 'S-ao-3', 'S-bc-m', 'S-bully-old', 'S-falcon-old', 'S-falcon', 'S-hoplite-old',
                  'S-hoplite', 'S-kim-100', 'S-kim-102', 'S-kim-105', 'S-kim-113', 'S-kim-116', 'S-kim-85d',
                  'S-kim-99m-old', 'S-kim-99m', 'S-kz-3a', 'S-lint-old', 'S-lint', 'S-lynx', 'S-mockingbird-old',
                  'S-mockingbird', 'S-sunrise-old']
goods_weapon_ID = ['AEK-919K', 'AH-94', 'AK-105', 'AK-74M', 'AKC-74', 'AKC-74Y', 'AKC', 'AKM', 'APS', 'Bintovka',
                   'BM-16', 'Browning', 'CBT-40', 'CKC-T', 'CKC', 'CKT-40', 'Cobray', 'COK-94', 'Cunami', 'DP', 'FN',
                   'Fort-12', 'Franchi', 'Gepard', 'HK', 'HK_1', 'IMI', 'IMI_1', 'IMI_2', 'Ingram', 'Karabin', 'Kbk',
                   'L85A1', 'L86A1', 'M1014', 'M16A1', 'M16A2', 'M16A3', 'M4A1', 'Mauser', 'Mauser_1', 'Mossberg', 'MP-133',
                   'MP-153', 'Obrez', 'P-92', 'PB', 'PMM', 'PP-2000', 'PP-91', 'PPS', 'Shorty',
                   'SIG', 'Spectre', 'Steyr', 'TO3-34', 'TT', 'vz68', 'walther', 'Walther_1', 'Winchester',
                   'Winchester_1']
goods_medic_a = [1 for i in range(44)]
for i in range(24):
    goods_medic_a.append(2)
goods_supplies_a = [900, 700, 700, 650, 600, 700, 600, 600, 750, 40, 240, 400, 200, 300, 300, 200, 150, 360, 1000, 550,
                    630, 400, 120, 650, 900, 650, 600, 1100, 950, 900, 40, 700, 650, 120, 550, 550, 800, 750, 40, 390,
                    70, 60, 110, 240, 150, 400, 400, 400, 800, 800, 1000, 70, 680, 840, 80, 240, 300, 840, 570, 430, 40,
                    40]
zones = [i for i in range(1, 120)]
zones_airdrop = [20, 34, 38, 41, 51, 56, 61, 63, 70, 74]
goods_airdrop_icon = ['9A-91', 'A-545', 'AA-12', 'AC', 'AEK-971', 'AH-94M', 'AK-103', 'AK-12', 'AK-15', 'AK-203',
                      'AK-308', 'AKM_1', 'ALK-22', 'Alpine', 'AM-17', 'AMB-17', 'AS-12', 'BCC-M', 'BCC', 'BCCK',
                      'BCK-94', 'Beretta', 'Beretta_1', 'Beretta_2', 'Caiga-12K', 'CB-98', 'CBD-C', 'CBD-M', 'CBD',
                      'CBY', 'Chiappa', 'Cobra', 'Colt', 'Colt_1', 'CP-1-10', 'CP-1', 'CP-2M', 'CP-3', 'CP-380',
                      'CP-3M', 'Crye', 'Desert', 'Desert_1', 'DSA-58', 'FAMAZ', 'FG-42', 'FN_1', 'FN_2', 'FN_3', 'FN_4',
                      'FN_5', 'FN_6', 'Glock', 'Glock_1', 'Glock_2', 'Grizzly', 'HK416', 'HK417', 'HK_10', 'HK_2',
                      'HK_3', 'HK_4', 'HK_5', 'HK_6', 'HK_7', 'HK_8', 'HK_9', 'Hladomet', 'Hladorez', 'IWI', 'L85A1_1',
                      'L86A1_1', 'L96A1', 'LR-300', 'Lyaguha', 'M1014_1', 'M1A', 'M1A_1', 'M249', 'M4', 'M40A5',
                      'M40A5_1', 'M4A1_1', 'MC-116M', 'MC-255', 'MC-558', 'McMillan', 'MG', 'Mk', 'MP-412', 'OC-14',
                      'OC-14M', 'OC-14M_1', 'OC-33', 'OC-62', 'Ognemet', 'Ognivo', 'OTL-03', 'PG-6', 'PKP', 'PKP_1',
                      'PMO-93', 'PP-19-01', 'PP-19', 'PP', 'PPK-20', 'Protecta', 'PTRD-M', 'QBZ-191',
                      'Rapira', 'RPD', 'RPG-7', 'RPK-16', 'RPK-74', 'RPK', 'RPL-20', 'RS-12', 'SA-58', 'Scorpion',
                      'SIG_1', 'SIG_2', 'SIG_3', 'SIG_4', 'Steyr_1', 'Steyr_2', 'Steyr_3', 'Steyr_4', 'Steyr_5',
                      'SW1911', 'TDI', 'TKB-0146M', 'Vintovka', 'Vityaz-CH', 'WA2000', 'ace-old', 'ace',
                      'albatross-stormtrooper', 'antares', 'ao-6-old', 'ao-6', 'apostle', 'avant-garde', 'beast-old',
                      'beast', 'bolt', 'centurion-old', 'centurion', 'chief', 'granite', 'hector', 'hound',
                      'jd-zivcas-2a', 'kim-x', 'kz-4', 'mule-old', 'mule', 'peresvet', 'punisher', 'reitar',
                      'saturn-old', 'saturn', 'sba-tank', 'skif-4', 'skif-4b', 'skif-5', 'zivcas',
                      'aborigine', 'albatross-laz', 'albatross-scout', 'altyn-t', 'ao-4-old', 'ao-4', 'ao-5', 'armai',
                      'bear', 'bully', 'centurion-vold', 'expedition', 'ghost-hunter', 'grenadier', 'huntsman',
                      'kim-122', 'kz-3b', 'legionnaire-old', 'legionnaire', 'magnet', 'misty-hunter', 'osh-old', 'osh',
                      'ploughman-old', 'ploughman', 'ratcatcher', 'reaper-old', 'reaper', 'reporter', 'samson-old',
                      'samson', 'saturn-vold', 'skif-2m-old', 'skif-2m', 'skif-4-old', 'skif-4-vold', 'skif-4b-old',
                      'snowstorm', 'spanner', 'suit-old', 'suit', 'sunrise', 'tonga', 'uran-old', 'uran', 'yorsh']
goods_airdrop_name = ['9А-91', 'А-545', 'AA-12', 'АС «Вал»', 'АЕК-971', 'АН-94М «Абакан»', 'АК-103', 'АК-12', 'АК-15',
                      'АК-203', 'АК-308', 'АКМ «Тишина»', 'АЛК-22 «Стрекоза»', 'Alpine TPG-1', 'АМ-17', 'АМБ-17',
                      'АШ-12', 'ВСС-М «Винторез»', 'ВСС «Винторез»', 'ВССК «Выхлоп»', 'ВСК-94', 'Beretta 92FS',
                      'Beretta 93R', 'Beretta Mx4 Storm', 'Protecta', 'СВ-98', 'СВД-С', 'СВД-М', 'СВД', 'СВУ',
                      'Chiappa Triple Crown', 'Cobra Two-Tone', 'Поношенный Colt Python', 'Colt Python', 'СР-1-10',
                      'СР-1 «Гюрза»', 'СР-2М «Вереск»', 'СР-3 «Вихрь»', 'CR-380', 'СР-3М', 'Crye Precision SIX12',
                      'Desert Eagle Mark VII', 'Desert Eagle Mark XIX', 'DSA-58', 'FAMAS G2', 'FG-42 «Хлыст»',
                      'Старый FN FAL', 'FN F2000', 'FN P90', 'FN FAL', 'FN F2000 Tactical', 'FN SCAR-H', 'Glock 17',
                      'Glock 18C', 'Glock 18X', 'Grizzly 8.5', 'HK416', 'HK417', 'FN SCAR SSR', 'Поношенная HK G3A1',
                      'HK G3A1', 'HK G36C', 'HK PSG1', 'HK MP5', 'HK UMP45', 'HK XM8S', 'HK XM8', '«Хладомет»',
                      '«Хладорез»', 'IWI Tavor X95', 'L85A1', 'L86A1', 'L96A1', 'LR-300', '«Лягуха»', 'M1014 Breacher',
                      'M1A', 'M1A FA', 'M249 SAW', 'M4 LB', 'M40A5', 'Поношенная M40A5', 'M4A1 CQC', 'МЦ-116М',
                      'МЦ-255', 'МЦ-558', 'McMillan CS5', 'MG 3', 'Mk 14 EBR', 'МР-412', 'ОЦ-14 «Гроза»',
                      'ОЦ-14М «Ураган»', 'ОЦ-14М «Разряд»', 'ОЦ-33 «Пернач»', 'ОЦ-62', 'Огнемет', '«Огниво»',
                      'ОТЛ-03 «Карбач»', 'РГ-6', 'Поношенный ПКП', 'ПКП «Печенег»', 'РМО-93', 'ПП-19-01 «Витязь»',
                      'ПП-19 «Бизон-2-01»', 'ПП «Орех»', 'Scorpion EVO III', 'Protecta', 'ПТРД-М',
                      'QBZ-191 «Буревестник»', '«Рапира»', 'РПД', 'РПГ-7', 'РПК-16', 'РПК-74', 'РПК', 'РПЛ-20',
                      'РШ-12', 'SA-58 CTC', 'Scorpion EVO III', 'SIG SG 550', 'SIG SG 550 Sniper', 'SIG MPX',
                      'SIG Sauer P320', 'Steyr AUG A3', 'Steyr AUG A2', 'Steyr AUG A1', 'Steyr AUG 9mm',
                      'Steyr AUG A3 9mm XS', 'SW1911', 'TDI KRISS Vector', 'ТКБ-0146М', 'Винтовка Гаусса',
                      '«Витязь-СН»', 'WA2000', 'Поношенный «Туз»', 'Экзоскелет «Туз»',
                      'Бронескелет «Альбатрос-Штурмовик»', 'Экзокостюм «Антарес»', 'Поношенный АО-6 «Кочевник»',
                      'УКАЗ АО-6 «Кочевник»', 'Сверхтяжелый бронекостюм «Апостол»', 'Бронекостюм «Авангард»',
                      'Поношенный «Зверобой»', 'Экзоброня «Зверобой»', 'Комбинезон «Ригель»', 'Поношенный «Центурион»',
                      'Бронескелет «Центурион»', 'Сверхтяжелый бронекостюм «Вождь»',
                      'Сверхтяжелый бронекостюм «Гранит»', 'Экзоскелет «Гектор»', 'Экзокостюм «Гончий»',
                      'Экзоброня JD ZIVCAS 2A', 'КИМ-Х «АТЛАС»', 'Бронекостюм «КЗ-4»', 'Поношенный «Мул»',
                      'Экзоскелет «Мул»', 'Комбинезон «Пересвет»', 'Бронекостюм «Каратель»',
                      'Сверхтяжелый бронекостюм «Рейтар»', 'Поношенный комбинезон «Сатурн»', 'Комбинезон «Сатурн»',
                      'SBA TANK', 'Бронекостюм «Скиф-4»', 'Бронекостюм «Скиф-4б»', 'Бронекостюм «Скиф-5»',
                      'Бронекостюм ZIVCAS M2-C', 'Экзоскелет «Абориген»', 'Бронескелет «Альбатрос-Лазутчик»',
                      'Бронескелет «Альбатрос-Разведчик»', 'Тяжелый комплект «Алтын-Т»', 'Поношенный АО-4 «Рейдер»',
                      'УКАЗ АО-4 «Рейдер»', 'УКАЗ АО-5 «Пилигрим»', 'Бронекостюм «Армай»', 'Экзоскелет «Медведь»',
                      'Tяжелый бронекостюм «Громила»', 'Поврежденный «Центурион»', 'Костюм «Экспедиция»',
                      'Бронекостюм «Призрачный охотник»', 'Экзоскелет «Гренадер»', 'Экзоброня «Егерь»',
                      'КИМ-122 «Аметист»', 'Бронекостюм «КЗ-3б»', 'Поношенный «Легионер»',
                      'Тяжелый бронекостюм «Легионер»', 'Комбинезон «Магнит»', 'Тяжелый бронекостюм «Туманный охотник»',
                      'Поношенный защитный костюм «Ош»', 'Защитный костюм «Ош»', 'Поношенный «Пахан»',
                      'Бронекостюм «Пахан»', 'Экзоброня «Крысолов»', 'Поношенный комбинезон «Жнец»',
                      'Комбинезон «Жнец»', 'Броня репортера', 'Поношенный экзоскелет «Самсон»', 'Экзоскелет «Самсон»',
                      'Поврежденный комбинезон «Сатурн»', 'Поношенный «Скиф-2м»', 'Бронекостюм «Скиф-2м»',
                      'Поношенный «Скиф-4»', 'Поврежденный «Скиф-4»', 'Поношенный «Скиф-4б»',
                      'Тяжелый бронекостюм «Идущий в метели»', 'УКАЗ «Спаннер»', 'Поношенная «Масть»',
                      'Экзоскелет «Масть»', 'Tяжелый бронекостюм «Восход»', 'Комбинезон «Тонга»',
                      'Поношенный комбинезон «Уран»', 'Комбинезон «Уран»', 'Защитный бронекостюм «Йорш»']
goods_airdrop_ID = ['9A-91', 'A-545', 'AA-12', 'AC', 'AEK-971', 'AH-94M', 'AK-103', 'AK-12', 'AK-15', 'AK-203',
                    'AK-308', 'AKM_1', 'ALK-22', 'Alpine', 'AM-17', 'AMB-17', 'AS-12', 'BCC-M', 'BCC', 'BCCK', 'BCK-94',
                    'Beretta', 'Beretta_1', 'Beretta_2', 'Caiga-12K', 'CB-98', 'CBD-C', 'CBD-M', 'CBD', 'CBY',
                    'Chiappa', 'Cobra', 'Colt', 'Colt_1', 'CP-1-10', 'CP-1', 'CP-2M', 'CP-3', 'CP-380', 'CP-3M', 'Crye',
                    'Desert', 'Desert_1', 'DSA-58', 'FAMAZ', 'FG-42', 'FN_1', 'FN_2', 'FN_3', 'FN_4', 'FN_5', 'FN_6',
                    'FN_7', 'Glock', 'Glock_1', 'Glock_2', 'Grizzly', 'HK416', 'HK417', 'HK_2', 'HK_3', 'HK_4', 'HK_5',
                    'HK_6', 'HK_7', 'HK_8', 'HK_9', 'Hladomet', 'Hladorez', 'IWI', 'L85A1_1', 'L86A1_1', 'L96A1',
                    'LR-300', 'Lyaguha', 'M1014_1', 'M1A', 'M1A_1', 'M249', 'M4', 'M40A5', 'M40A5_1', 'M4A1_1',
                    'MC-116M', 'MC-255', 'MC-558', 'McMillan', 'MG', 'Mk', 'MP-412', 'OC-14', 'OC-14M', 'OC-14M_1',
                    'OC-33', 'OC-62', 'Ognemet', 'Ognivo', 'OTL-03', 'PG-6', 'PKP', 'PKP_1', 'PMO-93', 'PP-19-01',
                    'PP-19', 'PP', 'PPK-20', 'Protecta', 'PTRD-M', 'QBZ-191', 'Rapira', 'RPD', 'RPG-7', 'RPK-16',
                    'RPK-74', 'RPK', 'RPL-20', 'RS-12', 'SA-58', 'Scorpion', 'SIG_1', 'SIG_2', 'SIG_3', 'SIG_4',
                    'Steyr_1', 'Steyr_2', 'Steyr_3', 'Steyr_4', 'Steyr_5', 'SW1911', 'TDI', 'TKB-0146M', 'Vintovka',
                    'Vityaz-CH', 'WA2000', 'M-ace-old', 'M-ace', 'M-albatross-stormtrooper', 'M-antares', 'M-ao-6-old',
                    'M-ao-6', 'M-apostle', 'M-avant-garde', 'M-beast-old', 'M-beast', 'M-bolt', 'M-centurion-old',
                    'M-centurion', 'M-chief', 'M-granite', 'M-hector', 'M-hound', 'M-jd-zivcas-2a', 'M-kim-x', 'M-kz-4',
                    'M-mule-old', 'M-mule', 'M-peresvet', 'M-punisher', 'M-reitar', 'M-saturn-old', 'M-saturn',
                    'M-sba-tank', 'M-skif-4', 'M-skif-4b', 'M-skif-5', 'M-zivcas', 'V-aborigine', 'V-albatross-laz',
                    'V-albatross-scout', 'V-altyn-t', 'V-ao-4-old', 'V-ao-4', 'V-ao-5', 'V-armai', 'V-bear', 'V-bully',
                    'V-centurion-vold', 'V-expedition', 'V-ghost-hunter', 'V-grenadier', 'V-huntsman', 'V-kim-122',
                    'V-kz-3b', 'V-legionnaire-old', 'V-legionnaire', 'V-magnet', 'V-misty-hunter', 'V-osh-old', 'V-osh',
                    'V-ploughman-old', 'V-ploughman', 'V-ratcatcher', 'V-reaper-old', 'V-reaper', 'V-reporter',
                    'V-samson-old', 'V-samson', 'V-saturn-vold', 'V-skif-2m-old', 'V-skif-2m', 'V-skif-4-old',
                    'V-skif-4-vold', 'V-skif-4b-old', 'V-snowstorm', 'V-spanner', 'V-suit-old', 'V-suit', 'V-sunrise',
                    'V-tonga', 'V-uran-old', 'V-uran', 'V-yorsh']
groups = ['Stalkers', 'Bandits', 'Soldiers', 'Duty', 'Freedom', 'Mercenaries', 'Monolith', 'Scientists', 'Shopot',
          'Clearsky']
zones_traders = [3, 4, 11, 16, 22, 24, 26, 28, 29, 35, 37, 42, 45, 54, 56, 65, 83, 87, 88, 98, 101, 110]
goods_novice = ['AK-74M', 'AKC-74', 'AKC-74Y', 'AKC', 'Bintovka', 'BM-16', 'CKC', 'CKT-40', 'DP', 'Gepard', 'IMI',
                'Karabin', 'M16A1', 'M16A2', 'M16A3', 'Mauser', 'Mossberg', 'MP-133', 'Obrez', 'P-92', 'PB',
                'PP-91', 'Shorty', 'TO3-34', 'TT', 'vz68', 'walther', 'Winchester', 'N-ao-1', 'N-ao-2-old', 'N-ao-2',
                'N-aurora-b', 'N-aurora-m', 'N-aurora', 'N-balloon-b', 'N-bc', 'N-coat', 'N-currant', 'N-disguise',
                'N-dogman', 'N-gas-mask-b', 'N-ip', 'N-jacket-b', 'N-jacket-m', 'N-jacket-mm', 'N-jacket-mm2',
                'N-jacket', 'N-key', 'N-kim-99-old', 'N-kim-99', 'N-kleptoman-old', 'N-kleptoman', 'N-kojak-b',
                'N-kz-1', 'N-kz-2', 'N-mole-b', 'N-mole', 'N-mushroom-old', 'N-mushroom', 'N-ozk',
                'N-rain', 'N-raincoat-b', 'N-raincoat-m', 'N-raincoat', 'N-scout', 'N-slide', 'N-stryker', 'N-suit-b',
                'N-trapper-old', 'N-trapper', 'N-worm']
goods_skilled = ['AEK-919K', 'AH-94', 'AK-105', 'AKM', 'APS', 'Browning', 'CBT-40', 'CKC-T', 'Cobray', 'COK-94',
                 'Cunami', 'FN', 'Fort-12', 'Franchi', 'HK', 'HK_1', 'IMI_1', 'IMI_2', 'Ingram', 'Kbk', 'L85A1', 'L86A1',
                 'M1014', 'M4A1', 'Mauser_1', 'MP-153', 'PMM', 'PP-2000', 'PPS', 'SIG', 'Spectre', 'Steyr', 'Walther_1',
                 'Winchester_1', 'S-altyn', 'S-ao-3-old', 'S-ao-3', 'S-bc-m', 'S-bully-old', 'S-falcon-old', 'S-falcon',
                 'S-hoplite-old', 'S-hoplite', 'S-kim-100', 'S-kim-102', 'S-kim-105', 'S-kim-113', 'S-kim-116',
                 'S-kim-85d', 'S-kim-99m-old', 'S-kim-99m', 'S-kz-3a', 'S-lint-old', 'S-lint', 'S-lynx',
                 'S-mockingbird-old', 'S-mockingbird', 'S-sunrise-old']
goods_veteran = ['9A-91', 'AC', 'AEK-971', 'AH-94M', 'AK-103', 'AK-12', 'AK-203', 'AKM_1', 'ALK-22', 'Alpine', 'BCC',
                 'Beretta', 'Beretta_1', 'Beretta_2', 'Caiga-12K', 'CB-98', 'CBD-C', 'CBD', 'CBY', 'Chiappa', 'Cobra',
                 'Colt', 'Colt_1', 'CP-1-10', 'CP-1', 'CP-2M', 'CP-3', 'Crye', 'Desert', 'FG-42', 'FN_1', 'FN_2',
                 'FN_3', 'Glock', 'Glock_1', 'Grizzly', 'HK416', 'HK_2', 'HK_3', 'HK_4', 'HK_5', 'HK_6', 'HK_7',
                 'L85A1_1', 'L86A1_1', 'Lyaguha', 'M1014_1', 'M1A', 'M1A_1', 'M249', 'M4', 'M40A5', 'M40A5_1', 'M4A1_1',
                 'MC-116M', 'MC-255', 'MC-558', 'MP-412', 'OC-14', 'OC-14M', 'OC-62', 'Ognemet', 'Ognivo', 'PG-6',
                 'PKP', 'PMO-93', 'PP-19-01', 'PP-19', 'PP', 'Protecta', 'Rapira', 'RPD', 'RPK-16', 'RPK-74', 'RPK',
                 'SIG_1', 'SIG_2', 'SIG_3', 'Steyr_1', 'Steyr_2', 'Steyr_3', 'Steyr_4', 'Steyr_5', 'SW1911',
                 'TKB-0146M', 'Vityaz-CH', 'V-aborigine', 'V-albatross-laz', 'V-albatross-scout', 'V-altyn-t',
                 'V-ao-4-old', 'V-ao-4', 'V-ao-5', 'V-armai', 'V-bear', 'V-bully', 'V-centurion-vold', 'V-expedition',
                 'V-ghost-hunter', 'V-grenadier', 'V-huntsman', 'V-kim-122', 'V-kz-3b', 'V-legionnaire-old',
                 'V-legionnaire', 'V-magnet', 'V-misty-hunter', 'V-osh-old', 'V-osh', 'V-ploughman-old', 'V-ploughman',
                 'V-ratcatcher', 'V-reaper-old', 'V-reaper', 'V-reporter', 'V-samson-old', 'V-samson', 'V-saturn-vold',
                 'V-skif-2m-old', 'V-skif-2m', 'V-skif-4-old', 'V-skif-4-vold', 'V-skif-4b-old', 'V-snowstorm',
                 'V-spanner', 'V-suit-old', 'V-suit', 'V-sunrise', 'V-tonga', 'V-uran-old', 'V-uran', 'V-yorsh']
goods_master = ['A-545', 'AA-12', 'AK-15', 'AK-308', 'AM-17', 'AMB-17', 'AS-12', 'BCC-M', 'BCCK', 'BCK-94', 'CBD-M',
                'CP-380', 'CP-3M', 'Desert_1', 'DSA-58', 'FAMAZ', 'FN_4', 'FN_5', 'FN_6', 'Glock_2', 'HK417', 'HK_10',
                'HK_8', 'HK_9', 'Hladomet', 'Hladorez', 'IWI', 'L96A1', 'LR-300', 'McMillan', 'MG', 'Mk', 'OC-14M_1',
                'OC-33', 'OTL-03', 'PKP_1', 'PPK-20', 'PTRD-M', 'QBZ-191', 'RPG-7', 'RPL-20', 'RS-12', 'SA-58',
                'Scorpion', 'SIG_4', 'TDI', 'Vintovka', 'WA2000', 'M-ace-old', 'M-ace', 'M-albatross-stormtrooper',
                'M-antares', 'M-ao-6-old', 'M-ao-6', 'M-apostle', 'M-avant-garde', 'M-beast-old', 'M-beast', 'M-bolt',
                'M-centurion-old', 'M-centurion', 'M-chief', 'M-granite', 'M-hector', 'M-hound', 'M-jd-zivcas-2a',
                'M-kim-x', 'M-kz-4', 'M-mule-old', 'M-mule', 'M-peresvet', 'M-punisher', 'M-reitar', 'M-saturn-old',
                'M-saturn', 'M-sba-tank', 'M-skif-4', 'M-skif-4b', 'M-skif-5', 'M-zivcas']
goods = ['9A-91', 'A-545', 'AA-12', 'AC', 'AEK-919K', 'AEK-971', 'AH-94', 'AH-94M', 'AK-103', 'AK-105', 'AK-12',
         'AK-15', 'AK-203', 'AK-308', 'AK-74M', 'AKC-74', 'AKC-74Y', 'AKC', 'AKM', 'AKM_1', 'ALK-22', 'Alpine', 'AM-17',
         'AMB-17', 'APS', 'AS-12', 'BCC-M', 'BCC', 'BCCK', 'BCK-94', 'Beretta', 'Beretta_1', 'Beretta_2', 'Bintovka',
         'BM-16', 'Browning', 'Caiga-12K', 'CB-98', 'CBD-C', 'CBD-M', 'CBD', 'CBT-40', 'CBY', 'Chiappa', 'CKC-T', 'CKC',
         'CKT-40', 'Cobra', 'Cobray', 'COK-94', 'Colt', 'Colt_1', 'CP-1-10', 'CP-1', 'CP-2M', 'CP-3', 'CP-380', 'CP-3M',
         'Crye', 'Cunami', 'Desert', 'Desert_1', 'DP', 'DSA-58', 'FAMAZ', 'FG-42', 'FN', 'FN_1', 'FN_2', 'FN_3', 'FN_4',
         'FN_5', 'FN_6', 'Fort-12', 'Franchi', 'Gepard', 'Glock', 'Glock_1', 'Glock_2', 'Grizzly', 'HK', 'HK416',
         'HK417', 'HK_1', 'HK_10', 'HK_2', 'HK_3', 'HK_4', 'HK_5', 'HK_6', 'HK_7', 'HK_8', 'HK_9', 'Hladomet',
         'Hladorez', 'IMI', 'IMI_1', 'IMI_2', 'Ingram', 'IWI', 'Karabin', 'Kbk', 'L85A1', 'L85A1_1', 'L86A1_1', 'L96A1',
         'LR-300', 'Lyaguha', 'M1014', 'M1014_1', 'M16A1', 'M16A2', 'M16A3', 'M1A', 'M1A_1', 'M249', 'M4', 'M40A5',
         'M40A5_1', 'M4A1', 'M4A1_1', 'Mauser', 'Mauser_1', 'MC-116M', 'MC-255', 'MC-558', 'McMillan', 'MG', 'Mk',
         'Mossberg', 'MP-133', 'MP-153', 'MP-412', 'Obrez', 'OC-14', 'OC-14M', 'OC-14M_1', 'OC-33', 'OC-62', 'Ognemet',
         'Ognivo', 'OTL-03', 'P-92', 'PB', 'PG-6', 'PKP', 'PKP_1', 'PMM', 'PMO-93', 'PP-19-01', 'PP-19',
         'PP-2000', 'PP-91', 'PP', 'PPK-20', 'PPS', 'Protecta', 'PTRD-M', 'QBZ-191', 'Rapira', 'RPD', 'RPG-7', 'RPK-16',
         'RPK-74', 'RPK', 'RPL-20', 'RS-12', 'SA-58', 'Scorpion', 'Shorty', 'SIG', 'SIG_1', 'SIG_2', 'SIG_3', 'SIG_4',
         'Spectre', 'Steyr', 'Steyr_1', 'Steyr_2', 'Steyr_3', 'Steyr_4', 'Steyr_5', 'SW1911', 'TDI', 'TKB-0146M',
         'TO3-34', 'TT', 'Vintovka', 'Vityaz-CH', 'vz68', 'WA2000', 'walther', 'Walther_1', 'Winchester',
         'Winchester_1', 'M-ace-old', 'M-ace', 'M-albatross-stormtrooper', 'M-antares', 'M-ao-6-old', 'M-ao-6',
         'M-apostle', 'M-avant-garde', 'M-beast-old', 'M-beast', 'M-bolt', 'M-centurion-old', 'M-centurion', 'M-chief',
         'M-granite', 'M-hector', 'M-hound', 'M-jd-zivcas-2a', 'M-kim-x', 'M-kz-4', 'M-mule-old', 'M-mule',
         'M-peresvet', 'M-punisher', 'M-reitar', 'M-saturn-old', 'M-saturn', 'M-sba-tank', 'M-skif-4', 'M-skif-4b',
         'M-skif-5', 'M-zivcas', 'N-ao-1', 'N-ao-2-old', 'N-ao-2', 'N-aurora-b', 'N-aurora-m', 'N-aurora',
         'N-balloon-b', 'N-bc', 'N-coat', 'N-currant', 'N-disguise', 'N-dogman', 'N-gas-mask-b', 'N-ip', 'N-jacket-b',
         'N-jacket-m', 'N-jacket-mm', 'N-jacket-mm2', 'N-jacket', 'N-key', 'N-kim-99-old', 'N-kim-99',
         'N-kleptoman-old', 'N-kleptoman', 'N-kojak-b', 'N-kz-1', 'N-kz-2', 'N-mole-b', 'N-mole',
         'N-mushroom-old', 'N-mushroom', 'N-ozk', 'N-rain', 'N-raincoat-b', 'N-raincoat-m', 'N-raincoat', 'N-scout',
         'N-slide', 'N-stryker', 'N-suit-b', 'N-trapper-old', 'N-trapper', 'N-worm', 'S-altyn', 'S-ao-3-old', 'S-ao-3',
         'S-bc-m', 'S-bully-old', 'S-falcon-old', 'S-falcon', 'S-hoplite-old', 'S-hoplite', 'S-kim-100', 'S-kim-102',
         'S-kim-105', 'S-kim-113', 'S-kim-116', 'S-kim-85d', 'S-kim-99m-old', 'S-kim-99m', 'S-kz-3a', 'S-lint-old',
         'S-lint', 'S-lynx', 'S-mockingbird-old', 'S-mockingbird', 'S-sunrise-old', 'V-aborigine', 'V-albatross-laz',
         'V-albatross-scout', 'V-altyn-t', 'V-ao-4-old', 'V-ao-4', 'V-ao-5', 'V-armai', 'V-bear', 'V-bully',
         'V-centurion-vold', 'V-expedition', 'V-ghost-hunter', 'V-grenadier', 'V-huntsman', 'V-kim-122', 'V-kz-3b',
         'V-legionnaire-old', 'V-legionnaire', 'V-magnet', 'V-misty-hunter', 'V-osh-old', 'V-osh', 'V-ploughman-old',
         'V-ploughman', 'V-ratcatcher', 'V-reaper-old', 'V-reaper', 'V-reporter', 'V-samson-old', 'V-samson',
         'V-saturn-vold', 'V-skif-2m-old', 'V-skif-2m', 'V-skif-4-old', 'V-skif-4-vold', 'V-skif-4b-old', 'V-snowstorm',
         'V-spanner', 'V-suit-old', 'V-suit', 'V-sunrise', 'V-tonga', 'V-uran-old', 'V-uran', 'V-yorsh']

viv = ['viv_boral', 'viv_forest', 'viv_humans', 'viv_night', 'viv_pizdec', 'viv_pizdec2', 'viv_under']

print(len(goods_armor_ID), len(goods_armor_icon))