from dir import *
from settings import *
f = open('Events_Story.ini', 'a', encoding='utf-8-sig')
for i in range(6):
        f.write(f'[EndVictory-{i}]\n'
                f'Step={30 + i}\n'
                f'Zona={a}\n'
                'Type=Info\n'
                'Img=gfx\icons\events\9.png\n'
                'TargetResourceImg=gfx\icons\goods\Merc-1.png\n'
                'Name=Победа\n'
                'Desc-Owner=Ezzzzzzz\n'
                'Desc-NonOwner=Ezzzzzzz\n'
                'ShowForOwner=False\n'
                'ShowForNonOwner=False\n'
                'AddToGameLog=False\n'
                'SoundFXForOwner=True\n'
                'SoundFXForOwnerFile=sfx\events\message.mp3\n'
                'SoundFXForNonOwner=True\n'
                'SoundFXForNonOwnerFile=sfx\events\message.mp3\n'
                f'NotWorkFractions=Mutants,Airdrop, Shopot, camp,base,boss\n'
                f'EventFlag=EndVictory\n'
                'EventFlagResult=EndVictory\n'
                'EventFlagStatusNeed=False\n'
                'EventFlagStatusSet=True\n'
                '\n')

        f.write(f'[EndLose-{i}]\n'
                f'Step={30 + i}\n'
                f'Zona={a}\n'
                'Type=Info\n'
                'Img=gfx\icons\events\9.png\n'
                'TargetResourceImg=gfx\icons\goods\Merc-1.png\n'
                'Name=Победа\n'
                'Desc-Owner=Ezzzzzzz\n'
                'Desc-NonOwner=Ezzzzzzz\n'
                'ShowForOwner=False\n'
                'ShowForNonOwner=False\n'
                'AddToGameLog=False\n'
                'SoundFXForOwner=True\n'
                'SoundFXForOwnerFile=sfx\events\message.mp3\n'
                'SoundFXForNonOwner=True\n'
                'SoundFXForNonOwnerFile=sfx\events\message.mp3\n'
                f'NotWorkFractions=Mutants,Airdrop,camp,,base,boss,{','.join(groups)}\n'
                f'EventFlag=EndLose\n'
                'EventFlagResult=EndLose\n'
                'EventFlagStatusNeed=False\n'
                'EventFlagStatusSet=True\n'
                '\n')
f.write(f'[Escape]\n'
        'Step=25\n'
        f'Zona={a}\n'
        'Status=True\n'
        'Type=ChangeStatusBrainMixer\n'
        'Img=gfx\icons\events\\4.png\n'
        'TargetResourceImg=gfx\icons\goods\Merc-1.png\n'
        'Name=Эвакуация\n'
        'Desc-Owner=Стала известна точка эвакуации\n'
        'Desc-NonOwner=Стала известна точка эвакуации\n'
        'ShowForOwner=True\n'
        'ShowForNonOwner=True\n'
        'AddToGameLog=False\n'
        'SoundFXForOwner=True\n'
        'SoundFXForOwnerFile=sfx\events\message.mp3\n'
        'SoundFXForNonOwner=True\n'
        'SoundFXForNonOwnerFile=sfx\events\message.mp3\n'
        f'NotWorkFractions=\n'
        '\n')
f.close()